import { createRailwayMap } from "./createRailwayMap";

const map = createRailwayMap();
describe("suite of tests for findShortestRoute", () => {
  test("known answers", () => {
    // expect(map.findShortestRoute("BERKHMD", "TRING")).toStrictEqual({
    //   distance: 5.994,
    //   nodes: ["BERKHMD", "TRING"],
    //   numTracks: 1,
    // });
    expect(map.findShortestRoute("BERKHMD", "HEMLHMP")).toStrictEqual({
      distance: 5.553,
      nodes: ["BERKHMD", "BORN412", "BONENDJ", "HEMLHMP"],
      numTracks: 3,
    });
    //   expect(map.findShortestRoute("DLTNN", "NORTONW")).toStrictEqual({
    //     distance: 22.716,
    //     nodes: [
    //       "DLTNN",
    //       "DLTN",
    //       "DLTNS",
    //       "DINSDAL",
    //       "TSDARPR",
    //       "ALLEURL",
    //       "ALLENSW",
    //       "EGLSCLF",
    //       "STOCCJN",
    //       "HRTBJN",
    //       "STOCTMS",
    //       "STOCTON",
    //       "NORTONS",
    //       "NORTONW",
    //     ],
    //     numTracks: 13,
    //   });
    //   expect(map.findShortestRoute("MNCRPIC", "CRDFCEN")).toStrictEqual({
    //     distance: 276.677,
    //     nodes: [
    //       "MNCRPIC",
    //       "ARDWCKJ",
    //       "LNGSTN",
    //       "SLDLJN",
    //       "MLDTHRD",
    //       "BAGE",
    //       "EDIDBRY",
    //       "GATLEY",
    //       "HLDG",
    //       "HLDGSJ",
    //       "STYAL",
    //       "WLMSL",
    //       "ALDEDGE",
    //       "CHELFD",
    //       "CHELFDL",
    //       "GOOSTRY",
    //       "HCHP",
    //       "SBCH",
    //       "CREWSBG",
    //       "CREWSGJ",
    //       "CREWEGL",
    //       "NANTWCH",
    //       "WRENBRY",
    //       "WCHR",
    //       "PREES",
    //       "WEMM",
    //       "YORTON",
    //       "HRLSCTX",
    //       "SHRWBCB",
    //       "SHRWBCJ",
    //       "SHRWBY",
    //       "SHRWEBJ",
    //       "SHRWSBJ",
    //       "DORNGTN",
    //       "CSTR",
    //       "MSHBRKX",
    //       "CRAVENA",
    //       "BRFLD",
    //       "LUDLOW",
    //       "WOFERTN",
    //       "LEOMNST",
    //       "MRTNONL",
    //       "SHIP",
    //       "HEREFRD",
    //       "TRAMINN",
    //       "PONTRLS",
    //       "ABRGVNY",
    //       "LTTLMLJ",
    //       "PONTYPL",
    //       "PANTEG",
    //       "CWMBRAN",
    //       "MAINDNJ",
    //       "MAINDWJ",
    //       "NWPTRTG",
    //       "GAERJ",
    //       "EBBWJ",
    //       "EBWVSGF",
    //       "MSHFILD",
    //       "RUMNYRB",
    //       "PENGAMS",
    //       "PENGAMJ",
    //       "MRLDJN",
    //       "LNGDYKJ",
    //       "CRDFE",
    //       "CRDFCEN",
    //     ],
    //     numTracks: 64,
    //   });
    expect(map.findShortestRoute("THURSO", "PENZNCE")).toStrictEqual({
      distance: 1455.756,
      nodes: [
        "THURSO",
        "GRGMASJ",
        "GRGMHLC",
        "SCSCLDR",
        "ALTNBRC",
        "FORSNRD",
        "KINBRAC",
        "KILDONN",
        "HELMSDL",
        "BRORDLC",
        "BRORA",
        "BRORALC",
        "DNROBIN",
        "GOLSPIE",
        "ROGART",
        "LAIRG",
        "LAIRSSH",
        "INVRSHN",
        "CULRAIN",
        "ARDGAY",
        "EDERTON",
        "TAIN",
        "FEARN",
        "IVRGRD",
        "ALNESS",
        "EVNTNIB",
        "DINGWAL",
        "CONONBR",
        "MUROORD",
        "BEAULY",
        "CLUNSIB",
        "IVRNBLC",
        "CLHY",
        "ROSEST",
        "IVRN410",
        "WSBG",
        "MILBRNJ",
        "CRAHALL",
        "CULDNMR",
        "MOYY",
        "TOMATIN",
        "SLOCHD",
        "CARRBDG",
        "AVIEMRE",
        "AVIEA29",
        "KNCRAIG",
        "KGUSSIE",
        "NWTM",
        "DALWHIN",
        "DLNSPDL",
        "DLNCRDH",
        "BLARATH",
        "PTLCHRY",
        "BLLINUG",
        "DUNKELD",
        "STNY",
        "PERTMU",
        "PERTH",
        "PERTHSO",
        "HILTONJ",
        "FRTEVOT",
        "AUCHTER",
        "GLNEGLS",
        "BLFD",
        "GRNLNNG",
        "DUNANE",
        "BGOALAN",
        "CORNTLC",
        "STIRLNN",
        "STIRLNG",
        "STIRLNM",
        "PLEAN",
        "LARBERN",
        "LARBERT",
        "LARBERJ",
        "CRMRSWJ",
        "GNHLLJN",
        "CMBR654",
        "CMBRNLD",
        "GRNFLDS",
        "GNFTSB",
        "GRNQNNJ",
        "GSHRSJN",
        "COATBDC",
        "COATBDJ",
        "WHIFLTN",
        "WHIFLET",
        "WHIFLTS",
        "MOSENXT",
        "MOSENY",
        "BNHOUSE",
        "MOSEDNY",
        "MOSEDFH",
        "MOSENDN",
        "MOSENDE",
        "HOLYTWN",
        "HOLYTNJ",
        "WISHAWC",
        "WISHAW",
        "LAWJ",
        "LAWJDPL",
        "CRLK",
        "LANARKJ",
        "CRSTRS",
        "CRSTRSS",
        "SYMNGTN",
        "ABINGTN",
        "BEATCKS",
        "BEATCK",
        "WMPHRAY",
        "LCKRBIE",
        "KRTLBDG",
        "COVELC",
        "KRKP863",
        "QNTNSHL",
        "GRETNAJ",
        "MSBD",
        "FLORSTN",
        "KGMRDDS",
        "CARLILY",
        "KGMR481",
        "KGMRJCN",
        "CARLCJN",
        "CARLILE",
        "CARLUJN",
        "CARLUBJ",
        "SOTHWAT",
        "PLPNUGL",
        "PNTH",
        "PNTHSJT",
        "CLFT",
        "SHAPHNS",
        "SHAPHQJ",
        "_SHAPSN",
        "SHAPSMT",
        "_SHAPSS",
        "TEBAY",
        "GRIGG",
        "OXENHLM",
        "MLNT",
        "CRNFNJN",
        "_CRNFSJ",
        "HESTBNK",
        "MORCMSJ",
        "LANCSTR",
        "OUBCKGL",
        "BAYHORS",
        "GSTANG",
        "BBGHGL",
        "PRSTNFJ",
        "PRSTSHL",
        "PRST",
        "PRSTRJN",
        "FRNGTNJ",
        "LEYLAND",
        "EUXTONJ",
        "BALSHWL",
        "WIGANNW",
        "WIGASJN",
        "SPRBJN",
        "BMFRLNJ",
        "GOLBRNJ",
        "WINWCKJ",
        "DALAMBR",
        "WRGTNBQ",
        "WRGTWOJ",
        "ACGJN",
        "WEAVERJ",
        "ACBG",
        "HARTFDJ",
        "HARTFD",
        "WNSFD",
        "CREWECY",
        "CREWE",
        "CREW543",
        "CREWESY",
        "CREWH44",
        "CREWBHJ",
        "MADELEY",
        "SLIGHTJ",
        "LBRDFJN",
        "STAFFDJ",
        "STAFFNJ",
        "STAFFRD",
        "STAFFSJ",
        "STAFTVJ",
        "PNKRDG",
        "FRASL",
        "BSBYJN",
        "WVRMTNJ",
        "WVRMPTN",
        "WVRMCST",
        "MNMRGRN",
        "COSELEY",
        "TIPTON",
        "WTLN",
        "DUDLPT",
        "SNDWDUD",
        "GALTILL",
        "GALTONJ",
        "SMTHKRS",
        "SOHONJ",
        "SOHOSJ",
        "BHAMNWS",
        "FIVEWYS",
        "UNVRSYB",
        "SELYOAK",
        "BOURNVL",
        "LIFODWJ",
        "KNORTON",
        "_KNORWL",
        "LONB",
        "BGRN",
        "BLACKWL",
        "BRMSGRV",
        "STKWKSJ",
        "SPTCHLL",
        "WORCPWY",
        "ABTSWDJ",
        "ASHCHRC",
        "ASHCWGF",
        "ASHC453",
        "CHLTNHS",
        "CHLTALC",
        "CHLTNHM",
        "BNWDJN",
        "GLOSTYJ",
        "GLOSTUF",
        "HARSLP",
        "STNDSHJ",
        "DURSLEY",
        "BRKRJUN",
        "CHFIELD",
        "YATE",
        "WSTLGHJ",
        "BRSTPWY",
        "FILTNEW",
        "DRDAYSJ",
        "BRSTLEJ",
        "BRSTLTM",
        "BRSTLWJ",
        "BDMNSTR",
        "PARSNST",
        "NAILSEA",
        "YATTON",
        "YATTGF",
        "YATTONL",
        "WORLE",
        "WORLEJ",
        "UPHILLJ",
        "HGHBRDG",
        "BRDGWTR",
        "COGLOAD",
        "TAUNEJN",
        "TAUNTON",
        "NTNFTZN",
        "WELISOM",
        "WELIXO",
        "TIVITNL",
        "TIVIPW",
        "TIVILP",
        "CWLYBDG",
        "EXETRRY",
        "EXETRSD",
        "EXETRST",
        "STRCROS",
        "DAWLSHW",
        "DAWLISH",
        "TEINMTH",
        "NABT",
        "NABTWJ",
        "DAINTNT",
        "TOTNES",
        "AISHXO",
        "IVYBDGE",
        "HEMERDN",
        "TVSTCKJ",
        "LARAJN",
        "LIPSONJ",
        "PLYMTH",
        "DEVNPRT",
        "DOCKYDP",
        "KEYHAM",
        "STBDXJN",
        "STBDXFR",
        "SASH",
        "STGRMNS",
        "MENHENT",
        "LISKARD",
        "STPNCVE",
        "LRGN",
        "BODMNPW",
        "LSTWUGL",
        "LSTWTHL",
        "PARR",
        "STAUSTL",
        "BGLWJN",
        "PROBUS",
        "TRURO",
        "REDRUTH",
        "CBORNE",
        "HAYLE",
        "STERTH",
        "LNGROCK",
        "PENZNCE",
      ],
      numTracks: 304,
    });
    //   expect(map.findShortestRoute("GRSTH", "WATFDJ")).toStrictEqual({ distance: 2.635, nodes: ["GRSTH", "WATFDN", "WATFDJ"], numTracks: 2 })
  });
});


